export const ROUTE_PATH = {
  ROOT: '/',
  ABOUT: '/about',
  BLOG: '/blog',
  BLOG_TAGS: '/blog/tags',
  BLOG_SHORT_TAGS: '/blog/short-tags',
  BLOG_CATEGORY: '/blog/category',
  BLOG_SHORT: '/blog/short',
  RSS: '/rss.xml',
  PRIVACY: '/privacy',
  PRIVACY_KPOP_KO: '/privacy/kpop/ko',
  PRIVACY_KPOP_EN: '/privacy/kpop/en',
  PRIVACY_KPOP_JP: '/privacy/kpop/jp',
  PRIVACY_KPOP_CN: '/privacy/kpop/cn',
  PRIVACY_AI_WALLPAPER_KO: '/privacy/ai-wallpaper/ko',
  PRIVACY_AI_WALLPAPER_EN: '/privacy/ai-wallpaper/en',
  PRIVACY_AI_WALLPAPER_JP: '/privacy/ai-wallpaper/jp',
  PRIVACY_EASY_DOTS_KO: '/privacy/easy-dots/ko',
  PRIVACY_EASY_DOTS_EN: '/privacy/easy-dots/en',
  PRIVACY_PIXEL_BLUR_KO: '/privacy/pixel-blur/ko',
  PRIVACY_PIXEL_BLUR_EN: '/privacy/pixel-blur/en',
  PRIVACY_POMODORO_FLOW_KO: '/privacy/pomodoro-flow/ko',
  PRIVACY_POMODORO_FLOW_EN: '/privacy/pomodoro-flow/en',
};
